apiVersion: batch/v1
kind: CronJob
metadata:
  name: adservice-warmup
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: adservice-warmup
            image: amiraniv/cron-job:v1.0
            env:
            - name: AD_SERVICE_HOST
              value: adservice
            - name: AD_SERVICE_PORT
              value: "9555"
          restartPolicy: OnFailure
